### PR TITLE
Place selected footprints only

### PR DESCRIPTION
**Pull request by icnagy**
Hi,

Thank you for these plugins, they really improve KiCad’s workflow!

I use the place footprints one quite often, find it invaluable to lay out front panel controls. However I found it to be a bit cumbersome when I only want to place a selection of footprints. (Disclaimer: I am new with KiCad so I might not be doing things the KiCad way) I either end up selecting more than one footprint before running the plugin and realising I only have to select one, or have to deselect already placed ones and/or hand-pick the ones I’d like to arrange. So with this change:
- you select the footprints to be placed
- open the plugin and select 'by reference’
- you only see the selected footprints listed 
- run the plugin and note that only the originally selected footprints are placed
(Apologies for my python code, I don't know python)

Hope you find it useful.

### CODE REVIEW

**Comment by MitjaNemec** [comment]
Thanks for your contribution. I'll have to review the code and UX, so more comments are likely to follow.

I like the idea but my first approach would be to implement this as a separate subset. So the user would have to chose in the first dialog from: By selection, By reference, By sheet. So at the moment I am not sure which approach is best.

**Comment by icnagy** [comment]
Thank you! Appreciate your time and feedback!

Tried to add a third button to the dialog, but I’m afraid it’s out of my reach. I got it to display, but no events fired.

**Comment by MitjaNemec** [comment]
> Tried to add a third button to the dialog, but I’m afraid it’s out of my reach. I got it to display, but no events fired.

I don't mind handling technical stuff. What is your opinion on UX in this case?

**Comment by icnagy** [comment]
👍  I don’t mind technical challenges, but noticed there are resources for some kind of form builder tool that I don’t have installed and I just poked around in the generated python files. Back-porting those changes to the form builder tool could become quite difficult.

About the UX: I don’t mind the third button, definitely much cleaner than having two slightly different behaviours under the same button.

> By selection, By reference, By sheet

Sounds good to me.

**Comment by MitjaNemec** [comment]
Yeah, you should not change computer generated code. I use wxFormBuilder version 3.9.0 from https://github.com/wxFormBuilder/wxFormBuilder/releases

**Comment by MitjaNemec** [comment]
Ok, it took me some time, but I've managed to implement this with dedicated UI so that you can select which footprint serves as a pivot. The code is at the moment in [MitjaNemec:place_by_selection](https://github.com/MitjaNemec/Kicad_action_plugins/tree/place_by_selection) branch.

 You might want to test it and report back. If everything is fine, I'll merge it to master and close this PR.

**Comment by icnagy** [comment]
I think it works really great! Hope others will find it helpful too! Nice work! Thank you!

**Comment by MitjaNemec** [comment]
Thanks.

**Pull request closed without merging**
