### PR TITLE
Replicate Drawings (graphic items, dimensions...)

### PR DESCRIPTION
**Pull request by EeliK**
Drawings can be replicated, too. I also added some comments if the implementation is unclear or something needs to be changed in the future.

### CODE REVIEW

**Comment by EeliK** [comment]
I added also a fix for the window finding issue. It's based on simple experimentation with wxWindow.GetName().

```
>>> import wx
>>> frames = wx.GetTopLevelWindows()
>>> for f in frames: print(f.GetName())
... 
KicadFrame
PcbFrame
SchematicFrame
LibeditFrame
ModEditFrame
PythonConsole
>>> 
```

**Comment by MitjaNemec** [comment]
Thanks. The wx frame handler search is really nice

**Comment by MitjaNemec** [comment]
You might want to push the wx frame handler fix also to InteractiveHtmlBom plugin

**Comment by EeliK** [comment]
> You might want to push the wx frame handler fix also to InteractiveHtmlBom plugin

... or maybe @qu1ck can just copypaste it because it's one-liner?
`
_pcbnew_frame = [x for x in wx.GetTopLevelWindows() if x.GetName() == 'PcbFrame'][0]`

**Comment by MitjaNemec** [comment]
I wanted to avoid bugging qu1ck as he is probably working on plugin/content manager. And as it is your solution, I did not want to open a PR myself and thus in effect stealing your solution. But if you don't mind I can do it as I know where this code is, as I browsed through InteractiveHtmlBom recently.

**Comment by EeliK** [comment]
I don't mind at all, it's basically just changing one function call so practically nothing for copyright...

**Comment by qu1ck** [comment]
I don't need to change my plugin as window detection code only works for v5.0 version and later ones have native plugin button support.

**Pull request merged**
