### PR TITLE
Feature/replicate layout on 5.99

### PR DESCRIPTION
**Pull request by Miceuz**
This is just a preview of hacks that I did to make it work on 5.99

### CODE REVIEW

**Comment by wudo94** [comment]
I read your KiCad setup is very unconventional. 
Is there any chance to run the replicate_layout with a easy-to-download-version of KiCad?

On my system I have installed the following Version:
```
Application: KiCad

Version: (5.99.0-6613-ge739d5ba65), release build

Libraries:
	wxWidgets 3.0.5
	libcurl/7.71.0 OpenSSL/1.1.1g (Schannel) zlib/1.2.11 brotli/1.0.7 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.41.0

Platform: Windows 10 (build 19041), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Oct 27 2020 10:12:11
	wxWidgets: 3.0.5 (wchar_t,wx containers,compatible with 2.8)
	Boost: 1.73.0
	OCE: 6.9.1
	Curl: 7.71.0
	ngspice: 32
	Compiler: GCC 10.2.0 with C++ ABI 1014

Build settings:
	KICAD_SCRIPTING=ON
	KICAD_SCRIPTING_MODULES=ON
	KICAD_SCRIPTING_PYTHON3=OFF
	KICAD_SCRIPTING_WXPYTHON=ON
	KICAD_SCRIPTING_WXPYTHON_PHOENIX=OFF
	KICAD_SCRIPTING_ACTION_MENU=ON
	BUILD_GITHUB_PLUGIN=ON
	KICAD_USE_OCE=ON
	KICAD_SPICE=ON
```
With this version i have the following issue if i run replicate layout with your changes:
image

In a second step i downloaded and installed the latest nightly build:
```
Application: KiCad

Version: (5.99.0-8543-g42cbcf7ef4), release build

Libraries:
	wxWidgets 3.0.5
	libcurl/7.71.0 OpenSSL/1.1.1g (Schannel) zlib/1.2.11 brotli/1.0.7 libidn2/2.3.0 libpsl/0.21.0 (+libidn2/2.3.0) libssh2/1.9.0 nghttp2/1.41.0

Platform: Windows 10 (build 19041), 64-bit edition, 64 bit, Little endian, wxMSW

Build Info:
	Date: Jan 22 2021 21:59:13
	wxWidgets: 3.0.5 (wchar_t,wx containers,compatible with 2.8)
	Boost: 1.73.0
	OCE: 6.9.1
	Curl: 7.71.0
	ngspice: 32
	Compiler: GCC 10.2.0 with C++ ABI 1014

Build settings:
	KICAD_SCRIPTING=ON
	KICAD_SCRIPTING_MODULES=ON
	KICAD_SCRIPTING_PYTHON3=OFF
	KICAD_SCRIPTING_WXPYTHON=ON
	KICAD_SCRIPTING_WXPYTHON_PHOENIX=OFF
	KICAD_SCRIPTING_ACTION_MENU=ON
	KICAD_USE_OCE=ON
	KICAD_SPICE=ON
```
With this version i have the following issue if i run replicate layout with your changes:
image

If the replicate layout tool worked with a ready-to-download version of KiCad 5.99 that would be perfect.

**Comment by Miceuz** [comment]
This is not meant as a proper fix, just a quick hack for whover finds it useful, it's a dirty hack. 

Windows nightlies are built using python2 and with no Phoenix support, this is a bit too much for me to dig as I was interested just to make this work for me because I needed the functionality. I encourage you to have a look at it yourself. The code is very easy to follow.

The first message you got meant that the plugin could not find object with such UUID. The second message has to do with particular wxPython calls used.

**Comment by MitjaNemec** [comment]
Thanks for the example. I'll probably merge it in a demo branch for all the 5.99 users and update the readme.

P.S. sorry for the delay, but my reponse time to non urgent items is quite long recently

**Comment by MitjaNemec** [comment]
Merged, and a notice is added to main README, where I mention your contribution. If you have any comments, just submit a PR I'll merge it.

Again, thanks for the example.

**Comment by Miceuz** [comment]
Thanks for merging!

**Pull request merged**
